### ISSUE TITLE
linux: Can't run examples. HCI.send blocks forever.

### ISSUE THREAD

**Issue by eicca** [currantlabs/ble#11] opened 2016-09-08 10:42 UTC
Hello,

I've tried to run scanner and explorer examples, but unfortunately they hang on `gatt.DefaultDevice()`. I looked deeper and it looks like that `select` https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L253 blocks forever.

My system:

```
-> uname -r
4.6.2-1-ARCH
```

Could you please give any tip about what is going wrong here?

Thanks!

**Comment by roylee17** [comment] 2016-09-08 15:38
Let's see if the following can get us a little bit further.  :)

1. Check if your system is running "bluetoothd", if yes, turn it off for now and see if that's the case.

2. Reset the HCI device in case it was in some bad status we couldn't recover from.
```
sudo hciconfig hci0 reset
sudo go run scanner/main.go
```

3. Check if your system was configured with bluetoooth at all.
```
sudo hciconfig hci0 up
sudo hcitool -i hci0 lescan
```

4. If the hcitool works while the examples are still not working, run the `hcidump` to log the packets for both cases (examples, and hcitool) for comparison/debugging.

```
sudo hcidump -i hci0
```

**Comment by eicca** [comment] 2016-09-13 13:33
Thanks for the help, @roylee17! Unfortunately it still doesn't work for me. I'm still getting stuck at `gatt.DefaultDevice()`.

hcitool and gatt library work fine on the same machine.

I'll try to dump the logs from hcitool, gatt and ble and compare them. I hope I'll find something.

**Comment by eicca** [comment] 2016-11-29 17:27
Just a little update: I tried to use **ble** on another Ubuntu linux machine and I experienced the same problem. Though, it worked just fine on the raspberry Pi.

I'll try to investigate more.

**Comment by deadprogram** [comment] 2016-12-28 16:35
Hi @eicca & @roylee17 I have the exact same issue on Ubuntu 14.04. with the latest ble package and the scanner example.

Attached is my hcidump file.

Thanks!
[scan.txt](https://github.com/currantlabs/ble/files/675877/scan.txt)

**Comment by deadprogram** [comment] 2016-12-28 18:39
FOr a little additional info, this where it gets "stuck": https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L253

**Comment by deadprogram** [comment] 2016-12-28 18:44
Called as part of the `Init()` https://github.com/currantlabs/ble/blob/master/linux/device.go#L21 to be clear.

**Comment by deadprogram** [comment] 2016-12-30 09:12
Oops, I had forgotten the hcidump for my successful `sudo hcitool -i hci0 lescan` run. Here it is.
[hcitool.txt](https://github.com/currantlabs/ble/files/678468/hcitool.txt)

**Comment by deadprogram** [comment] 2017-01-04 15:35
It is this `Send()` here that suspends forever: https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L179

**Comment by deadprogram** [comment] 2017-01-04 16:09
Last comment, hopefully. the latest currantlabs fork of gatt works fine on the same machine, just not this package.

**Comment by roylee17** [comment] 2017-01-05 05:24
Sorry for the late response. 

We should be able to fix it quickly once we can reproduce it.
I just installed a vagrant box (virtualbox) with ubuntu-14.04 with updated bluez, to reproduce it, but it didn't happen.

Is it 100% reproducible in your config, or it happens sometime?

Can you show the following configuration for reference?

```
vagrant@vagrant:~/go/src/github.com/currantlabs/ble/examples/basic/scanner$ dpkg -s bluez|grep Version
Version: 4.101-0ubuntu13.1
```

```
vagrant@vagrant:~/go/src/github.com/currantlabs/ble/examples/basic/scanner$ uname -a
Linux vagrant 3.13.0-103-generic #150-Ubuntu SMP Thu Nov 24 10:34:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
Version prints the Go version, as reported by runtime.Version.
vagrant@vagrant:~/go/src/github.com/currantlabs/ble/examples/basic/scanner$ go version
go version go1.7 linux/amd64
```

```
vagrant@vagrant:~/go/src/github.com/currantlabs/ble/examples/basic/scanner$ git show --oneline
65396cf Merge pull request #21 from syoder/flush-socket-after-bind
```


```
vagrant@vagrant:~/go/src/github.com/currantlabs/ble/examples/basic/scanner$ sudo ./main
Scanning for 5s...
[68:d9:3c:7c:72:83] C -81: MD: 4C000906031F0A000111
[68:d9:3c:7c:72:83] C -81: MD: 4C000906031F0A000111
[65:7b:59:12:5a:40] C -100:
[65:7b:59:12:5a:40] C -98:
[68:d9:3c:7c:72:83] C -87: MD: 4C000906031F0A000111
[68:d9:3c:7c:72:83] C -81: MD: 4C000906031F0A000111
[68:d9:3c:7c:72:83] C -81: MD: 4C000906031F0A000111
^Ccanceled
```

**Comment by roylee17** [comment] 2017-01-05 07:33
In your hcidump, there is  a **vendor specific command** at the end of the initialization sequence.
And after that the device is not responding to our first command.

```
175 < HCI Command: Vendor (0x3f|0x003f) plen 0
176 > HCI Event: Command Complete (0x0e) plen 4
177     Vendor (0x3f|0x003f) ncmd 1

178 < HCI Command: Read BD ADDR (0x04|0x0009) plen 0
```

Can you attach the hcidump (with -t) for the following experiment:
```
hciconfig down hci0
hcidump -t hci0 (another terminal or redirect to file)
hciconfig up hci0
hcitool -i hci0 lescan run
```

Just in case, experiment with hci reset as well.
```
hciconfig down hci0
hcidump -t hci0 (another terminal or redirect to file)
hciconfig reset hci0
hcitool -i hci0 lescan run
```

Let's see if that vendor specific command shows up, and what need to be done before it takes/responds to the next command (some... delay?).

In that case, hack our init() call to wait a little bit and see if that 's the case: 
Add `time.Sleep(time.Second*5)` after `socket.NewSocket(h.id)`
https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L138

**Comment by deadprogram** [comment] 2017-01-05 11:09
Thanks for looking into this. 

Here are my system settings:

```
$ dpkg -s bluez|grep Version                                                                                           
Version: 4.101-0ubuntu13.1
$ uname -a                                                                                                             
Linux ron-XPS-13-9343 4.4.0-57-generic #78~14.04.1-Ubuntu SMP Sat Dec 10 00:14:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ go version                                                                                                           
go version go1.7.4 linux/amd64
$ git show --oneline
65396cf Merge pull request #21 from syoder/flush-socket-after-bind
```

Looks like we have different kernel versions?

I performed the dumps as requested. Note that the syntax for `hciconfig down hci0` is actually `hciconfig -a hci0 down` etc. In any case, there was no occurrence of `Vendor` anywhere in either log.

Lastly, I added the suggested `time.Sleep()` but it had no effect.

[hcidump2.txt](https://github.com/currantlabs/ble/files/687072/hcidump2.txt)

**Comment by roylee17** [comment] 2017-01-05 18:46
Okay, let's where does that vendor command come.

 https://github.com/currantlabs/ble/commit/7445c31b838a5f554f844c4a0d8d2a5846cb10fa

Can you apply this commit, and run it with the log enabled (`sudo LOGXI=* ./scanner`), and also hcidump with -t at the same time.

This add a few 1-second delay, and dump the raw traffic we send to HCI.
Cross reference the timestamp from hcidump, we should be able to find where and then figure out why.

**Comment by deadprogram** [comment] 2017-01-06 14:25
OK here is the output:

```
$ sudo LOGXI=* ./scanner                                                                                               
15:22:58.446404 INF hci Creating socket
15:22:59.446763 DBG socket down hci
15:23:00.448324 DBG socket up hci
15:23:01.496202 DBG socket down2 hci
15:23:02.497270 DBG socket bind hci user_channel
15:23:03.498104 DBG socket poll previous left over
15:23:04.518374 INF hci Creating sktloop
15:23:05.518675 INF hci Send init seq
15:23:05.518813 DBG socket Write raw: [01 09 10 00]
```

And here is the dump file: 
[hcidump3.txt](https://github.com/currantlabs/ble/files/690097/hcidump3.txt)

**Comment by roylee17** [comment] 2017-01-06 16:59
A few quick experiments.

Comment out those three "up and down" in our code.

From 
https://github.com/currantlabs/ble/commit/7445c31b838a5f554f844c4a0d8d2a5846cb10fa#diff-a58a7abf497cdab9034b34b85b0800bfR93

To
https://github.com/currantlabs/ble/commit/7445c31b838a5f554f844c4a0d8d2a5846cb10fa#diff-a58a7abf497cdab9034b34b85b0800bfR111

Use hciconfig to init the device before invoking the scanner binary.
(with hcidump)
```
sudo hciconfig down
sudo hciconfig up
sudo hciconfig down
```

and again

```
sudo hciconfig reset
sudo hciconfig down
```

**Comment by deadprogram** [comment] 2017-01-06 18:00
When I remove these lines https://github.com/currantlabs/ble/blob/debug/issue_11/linux/hci/socket/socket.go#L93-L111 I receive this error:

```
$ sudo LOGXI=* ./scanner                                                                                               
18:56:53.431004 INF hci Creating socket
18:56:54.431364 DBG socket bind hci user_channel
2017/01/06 18:56:54 can't new device : can't init hci: no devices available: (hci0: can't bind socket to hci user channel: device or resource busy)
```

**Comment by roylee17** [comment] 2017-01-06 18:05
The device state at the time of being binded with HCI_USER_CHANNEL must be **down**.

After `hciconfig hci down` in both cases, check again and see if the state is really **down**.

**Comment by deadprogram** [comment] 2017-01-06 18:15
I forgot the syntax is `sudo hciconfig -a hci0 down` etc. My bad.

In both cases, the log is quite short:

```
HCI sniffer - Bluetooth packet analyzer ver 2.5
device: hci0 snap_len: 1500 filter: 0xffffffffffffffff
2017-01-06 19:11:18.680933 < HCI Command: Read BD ADDR (0x04|0x0009) plen 0
```

With the following output:

```
$ sudo LOGXI=* ./scanner 
19:11:14.659604 INF hci Creating socket
19:11:15.659995 DBG socket bind hci user_channel
19:11:16.660293 DBG socket poll previous left over
19:11:17.680607 INF hci Creating sktloop
19:11:18.680823 INF hci Send init seq
19:11:18.680897 DBG socket Write raw: [01 09 10 00]
```

**Comment by roylee17** [comment] 2017-01-06 18:41
Then this is really strange. The very first thing we tried to talk with device after initialization, it doesn't respond.

I suspect the particular driver of that particular kernel version is doing something differently when it comes to HCI_USER_CHANNEL.

But you mentioned **gatt**, which also uses HCI_USER_CHANNEL does work in your system.
Can you help to hcidump **gatt**.

And also `strace` both ble binary and gatt binary.

I'll try if I can install that kernel on my ubuntu later. Or if its easier that you can try other kernel version.

3.13 on ubuntu works. And I've been using 3.17, 4.1, 4.8 and and a few other version on my gentoo box without problem.

**Comment by deadprogram** [comment] 2017-01-06 19:09
OK here is my gatt run:

```
$ sudo ./discoverer 
2017/01/06 20:07:29 dev: hci0 up
2017/01/06 20:07:29 dev: hci0 down
2017/01/06 20:07:29 dev: hci0 opened
State: PoweredOn
scanning...

Peripheral ID:C1:CD:28:CF:12:8E, NAME:(2B-128E)
  Local Name        = 2B-128E
  TX Power Level    = 246
  Manufacturer Data = []
  Service Data      = []

Peripheral ID:EE:A3:19:85:15:8C, NAME:(2B-158C)
  Local Name        = 2B-158C
  TX Power Level    = 246
  Manufacturer Data = []
  Service Data      = []

Peripheral ID:F3:F2:6D:55:71:08, NAME:(BB-7108)
  Local Name        = BB-7108
  TX Power Level    = 6
  Manufacturer Data = [51 48]
  Service Data      = []
```

and the associated hcidump file: 
[hcidumpgatt.txt](https://github.com/currantlabs/ble/files/690609/hcidumpgatt.txt)

**Comment by roylee17** [comment] 2017-01-06 19:30
https://github.com/currantlabs/ble/compare/debug/issue_11

I revert the device/socket handling. Give it shot and see if anything changes

**Comment by deadprogram** [comment] 2017-01-06 19:30
Here is the strace from the gatt run: 
[tracegatt.txt](https://github.com/currantlabs/ble/files/690652/tracegatt.txt)

Here is the strace from the scanner: 
[scanner-trace.txt](https://github.com/currantlabs/ble/files/690664/scanner-trace.txt)

**Comment by deadprogram** [comment] 2017-01-06 19:37
Here is the scanner strace after a `sudo hciconfig -a hci0 reset && sudo hciconfig -a hci0 down`:

[scanner-trace-after-reset.txt](https://github.com/currantlabs/ble/files/690682/scanner-trace-after-reset.txt)

**Comment by deadprogram** [comment] 2017-01-06 19:42
Here is the strace form the scanner after the reverted code:
[scanner-after-revert.txt](https://github.com/currantlabs/ble/files/690695/scanner-after-revert.txt)

**Comment by roylee17** [comment] 2017-01-06 19:44
So the reverted one still not working? BTW, I got Slack back on. Let's work on this more interactively.

**Comment by eicca** [comment] 2017-01-06 21:39
The reverted code isn't working for me either. I'll to reproduce the issue with virtualbox so it'd be easier to debug.

**Comment by deadprogram** [comment] 2017-01-06 22:03
I have the same problem also on my Intel Edison running Yocto, so it is not just an Ubuntu issue:

```
root@howtocode:~# hciconfig -a hci0 down
root@howtocode:~# ./robots/scanner 
2017/01/06 21:59:08 dev: hci0 up
2017/01/06 21:59:08 dev: hci0 down
2017/01/06 21:59:08 dev: hci0 can't bind to hci user channel, err: invalid argument.
2017/01/06 21:59:08 dev: hci0 opened
^C
root@howtocode:~# hcitool lescan
Could not open device: No such device
root@howtocode:~# hciconfig -a hci0 up  
root@howtocode:~# hcitool lescan                                                                                       
LE Scan ...
7D:22:0A:9F:01:82 (unknown)
F3:F2:6D:55:71:08 (unknown)
F3:F2:6D:55:71:08 BB-7108
C1:CD:28:CF:12:8E (unknown)
EE:A3:19:85:15:8C (unknown)
EE:A3:19:85:15:8C 2B-158C
7D:22:0A:9F:01:82 (unknown)
C1:CD:28:CF:12:8E 2B-128E
^Croot@howtocode:~# hciconfig -a hci0 down                                                                             
root@howtocode:~# ./robots/scanner                                                                             
2017/01/06 22:00:58 dev: hci0 up
2017/01/06 22:00:58 dev: hci0 down
2017/01/06 22:00:58 dev: hci0 can't bind to hci user channel, err: invalid argument.
2017/01/06 22:00:58 dev: hci0 opened
```

**Comment by roylee17** [comment] 2017-01-06 22:45
@deadprogram , this might be different.  I seemed to remember Edison Yocto was using an earlier kernel that doesn't support HCI_USER_CHANNEL yet.

In **gatt**, we used to fall back to use RAW channel in that case. But, that means we might have some subtle behavior as Kernel is also talking to the device in the background.

You can try if that's the case by changing the `unix.HCI_CHANNEL_USER` to `HCI_CHANNEL_RAW`. And the reverted version should work, I guess.

**Comment by deadprogram** [comment] 2017-01-06 23:08
HCI_CHANNEL_RAW got rid of the `can't bind to hci user channel, err: invalid argument.` error. New code did not get any further as far as scanning, however.

**Comment by deadprogram** [comment] 2017-01-07 11:44
I note that when I switch gatt discoverer to use HCI_CHANNEL_RAW it has the same "sit forever without scanning" behavior on both my Ubuntu notebook and my Edison as the ble scanner does.

**Comment by roylee17** [comment] 2017-01-07 17:48
Another two hacks, just to see if we can move any further:
1. Escape that select with a timeout.
```
	case <-time.After(time.Second):
		return nil, nil
```
https://github.com/currantlabs/ble/blob/master/linux/hci/hci.go#L257

2. Replace the h.init() with hard coded values.
``` 
	h.bufCnt = 7
	h.bufSize = 0x1b
	// h.init()
```

This should give us exactly same hcidump we got with `hciconfig+hcitool lescan`.

**Comment by deadprogram** [comment] 2017-01-07 20:46
OK, here is my log output:

```
$ sudo LOGXI=* ./scanner 
21:43:35.302067 DBG socket down hci
21:43:36.302430 DBG socket up hci
21:43:37.350326 DBG socket down2 hci
21:43:38.351446 DBG socket bind hci user_channel
21:43:39.351734 DBG socket poll previous left over
21:43:39.372037 DBG socket Write
   raw: [01 06 20 0F 20 00 20 00 00 00 00 00 00 00 00 00 00 07 00]
```

Attached is my hcidump file: 
[hcidump6.txt](https://github.com/currantlabs/ble/files/691692/hcidump6.txt)

**Comment by roylee17** [comment] 2017-01-07 21:37
Honestly, I'm really running out of idea about what's going on. At least one of those experiments we did should make some difference.

We're stuck at the early stage that the very first thing we send to the kernel is not responded. So we don't even have a chance to do anything wrong with the response yet.

Reverting the socket/device package should give us the identical handling with what **gatt** is doing up to that point.

Probably the last attempt I can think of - try the reverted version again with different condition:

  1. with the hci0 device down.
  2. with the hci0 device up.

They will hit different paths in the socket package.

**Comment by deadprogram** [comment] 2017-01-14 10:36
I upgraded my Dell XPS 13 (Dell Developer Notebook) to Ubuntu 16.04:

```
$ uname -a
Linux ron-XPS-13-9343 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

However, I still have the same problem with ble. I am able to scan using `hcitool`:

```
$ sudo hciconfig -a hci0 reset && sudo hciconfig -a hci0 up
$ sudo hcitool -i hci0 lescan
LE Scan ...
EE:A3:19:85:15:8C (unknown)
EE:A3:19:85:15:8C 2B-158C
54:44:EE:EC:76:97 (unknown)
54:44:EE:EC:76:97 (unknown)
C1:CD:28:CF:12:8E (unknown)
C1:CD:28:CF:12:8E 2B-128E
F3:F2:6D:55:71:08 (unknown)
F3:F2:6D:55:71:08 BB-7108
```

I compiled scanner using the last commit to both the `debug/issue_11` branch as well as the `master` branch, but neither one was able to do the scanning.

```
$ sudo ./scanner
2017/01/14 11:14:25 dev: hci0 up
2017/01/14 11:14:25 dev: hci0 reset
2017/01/14 11:14:25 dev: hci0 down
2017/01/14 11:14:25 dev: hci0 opened
```

Attached is the hcidump file from running the scanner from the `debug/issue_11` branch. I see that vendor command as the last command sent before it stops responding:

```
2017-01-14 10:57:52.511758 > HCI Event: Command Complete (0x0e) plen 4
    Vendor (0x3f|0x003f) ncmd 1
```

[hcidump1604-1.txt](https://github.com/currantlabs/ble/files/705866/hcidump1604-1.txt)

Likewise, I am completely baffled here. Obviously the hardware itself "works" but there is something in there somewhere in ble not quite handling things in the same way.

**Comment by deadprogram** [comment] 2017-01-14 10:39
My new bluez version:

```
$ dpkg -s bluez|grep Version
Version: 5.37-0ubuntu5
```

**Comment by deadprogram** [comment] 2017-01-14 10:50
Here is the hciscan dump of the successful `sudo hciconfig -a hci0 reset && sudo hciconfig -a hci0 up` and `sudo hcitool lescan` commands.

I notice that it does start with the same vendor command, but then immediately issues a reset:

```
2017-01-14 11:45:58.235923 > HCI Event: Command Complete (0x0e) plen 4
    Vendor (0x3f|0x003f) ncmd 1
2017-01-14 11:45:58.249971 > HCI Event: Command Complete (0x0e) plen 4
    Reset (0x03|0x0003) ncmd 2
    status 0x00
```

I do not know enough about the low-level protocol here, but looks interesting?

[hcidump1604-lescan.txt](https://github.com/currantlabs/ble/files/705873/hcidump1604-lescan.txt)

**Comment by roylee17** [comment] 2017-01-14 10:55
The things bothers me is that I tried to reverted blue to the point that should work as gatt, and they still behave differently. The hcidump from your gatt discover also has a vendor command presents, but it works fine. 

You have a spare machine that can ship to me? I can spend a day or two dedicated on it.

**Comment by roylee17** [comment] 2017-01-14 11:05
```
func (h *HCI) init() error {
   h.Send(&cmd.Reset{}, nil)
```
So give it a shot, reset it in the h.init().

**Comment by deadprogram** [comment] 2017-01-14 11:10
It worked!!

```
$ sudo ./scanner                                                                                                       
2017/01/14 12:07:36 dev: hci0 up
2017/01/14 12:07:36 dev: hci0 reset
2017/01/14 12:07:36 dev: hci0 down
2017/01/14 12:07:36 dev: hci0 opened
Scanning for 5s...
[ee:a3:19:85:15:8c] C -74:
[ee:a3:19:85:15:8c] C -74: Name: 2B-158C, Svcs: [22bb746f2ba075542d6f726568705327]
[f3:f2:6d:55:71:08] C -44: MD: 3330
[f3:f2:6d:55:71:08] C -44: Name: BB-7108, Svcs: [22bb746f2ba075542d6f726568705327], MD: 3330
[c1:cd:28:cf:12:8e] C -67:
...
```

I thought it looked "interesting". 

Wow, thank you for persevering thru to find out what was happening here!

**Comment by deadprogram** [comment] 2017-01-14 11:17
That same one line change when made to `master` branch also worked to scan as expected.

**Comment by deadprogram** [comment] 2017-01-14 12:13
I've submitted a PR with the change here https://github.com/currantlabs/ble/pull/26. @eicca can you please check to see if this works for you?

**Comment by roylee17** [comment] 2017-01-14 17:40
Thanks for both of you. Especially @deadprogram for his persistence and patience tracing through and resolving the issue. :)

**Comment by deadprogram** [comment] 2017-01-14 19:32
Don't forget to close this issue now, and thanks again.

**Closed** 2017-01-14 19:39 UTC
